#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GordiTEC
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Cafeteria")]
	public partial class SPConexionDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public SPConexionDataContext() : 
				base(global::GordiTEC.Properties.Settings.Default.CafeteriaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SPConexionDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPConexionDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPConexionDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SPConexionDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarCaja")]
		public int insertarCaja([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Monto", DbType="Decimal(10,2)")] System.Nullable<decimal> monto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), monto, idEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarArticulosTicket")]
		public int insertarArticulosTicket([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idProducto, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTicket, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cantidad", DbType="Int")] System.Nullable<int> cantidad)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idProducto, idTicket, cantidad);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarGorditasCompleto")]
		public ISingleResult<mostrarGorditasCompletoResult> mostrarGorditasCompleto()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarGorditasCompletoResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarNombreYMatricula")]
		public ISingleResult<mostrarNombreYMatriculaResult> mostrarNombreYMatricula([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] ref string res, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] ref System.Nullable<int> resA)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), res, resA);
			res = ((string)(result.GetParameterValue(0)));
			resA = ((System.Nullable<int>)(result.GetParameterValue(1)));
			return ((ISingleResult<mostrarNombreYMatriculaResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.iniciarSesion")]
		public int iniciarSesion([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(60)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(60)")] string contraseña, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(60)")] ref string res)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), usuario, contraseña, res);
			res = ((string)(result.GetParameterValue(2)));
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarTicketUno")]
		public int insertarTicketUno([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpleado);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.ultimoTicket")]
		public ISingleResult<ultimoTicketResult> ultimoTicket()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<ultimoTicketResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarTicketDos")]
		public ISingleResult<mostrarTicketDosResult> mostrarTicketDos([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTicket)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idTicket);
			return ((ISingleResult<mostrarTicketDosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarTotal")]
		public ISingleResult<mostrarTotalResult> mostrarTotal()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarTotalResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarTicketTres")]
		public int mostrarTicketTres([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Total", DbType="Decimal(10,2)")] System.Nullable<decimal> total, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Decimal(10,2)")] System.Nullable<decimal> montoEntregado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Cambio", DbType="Decimal(10,2)")] System.Nullable<decimal> cambio, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idTicket)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), total, montoEntregado, cambio, idTicket);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarCorte")]
		public ISingleResult<mostrarCorteResult> mostrarCorte([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Fecha", DbType="DateTime")] System.Nullable<System.DateTime> fecha)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpleado, fecha);
			return ((ISingleResult<mostrarCorteResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.insertarEmpleados")]
		public int insertarEmpleados([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Nombre", DbType="VarChar(30)")] string nombre, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="App", DbType="VarChar(30)")] string app, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Apm", DbType="VarChar(30)")] string apm, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Usuario", DbType="VarChar(50)")] string usuario, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Contraseña", DbType="VarChar(15)")] string contraseña, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Permiso", DbType="Char(2)")] string permiso)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), nombre, app, apm, usuario, contraseña, permiso);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.mostrarEmpleados")]
		public ISingleResult<mostrarEmpleadosResult> mostrarEmpleados()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<mostrarEmpleadosResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.eliminarEmpleados")]
		public int eliminarEmpleados([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> idEmpleado)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), idEmpleado);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class mostrarGorditasCompletoResult
	{
		
		private int _Codigo_producto;
		
		private string _Nombre_del_producto;
		
		private string _Guiso;
		
		private decimal _Precio_de_venta;
		
		public mostrarGorditasCompletoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Codigo producto]", Storage="_Codigo_producto", DbType="Int NOT NULL")]
		public int Codigo_producto
		{
			get
			{
				return this._Codigo_producto;
			}
			set
			{
				if ((this._Codigo_producto != value))
				{
					this._Codigo_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre del producto]", Storage="_Nombre_del_producto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Nombre_del_producto
		{
			get
			{
				return this._Nombre_del_producto;
			}
			set
			{
				if ((this._Nombre_del_producto != value))
				{
					this._Nombre_del_producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guiso", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guiso
		{
			get
			{
				return this._Guiso;
			}
			set
			{
				if ((this._Guiso != value))
				{
					this._Guiso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Precio de venta]", Storage="_Precio_de_venta", DbType="Decimal(10,2) NOT NULL")]
		public decimal Precio_de_venta
		{
			get
			{
				return this._Precio_de_venta;
			}
			set
			{
				if ((this._Precio_de_venta != value))
				{
					this._Precio_de_venta = value;
				}
			}
		}
	}
	
	public partial class mostrarNombreYMatriculaResult
	{
		
		private string _nombreEmpleado;
		
		private int _idEmpleado;
		
		public mostrarNombreYMatriculaResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreEmpleado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombreEmpleado
		{
			get
			{
				return this._nombreEmpleado;
			}
			set
			{
				if ((this._nombreEmpleado != value))
				{
					this._nombreEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int NOT NULL")]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this._idEmpleado = value;
				}
			}
		}
	}
	
	public partial class ultimoTicketResult
	{
		
		private System.Nullable<int> _Column1;
		
		public ultimoTicketResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="", Storage="_Column1", DbType="Int")]
		public System.Nullable<int> Column1
		{
			get
			{
				return this._Column1;
			}
			set
			{
				if ((this._Column1 != value))
				{
					this._Column1 = value;
				}
			}
		}
	}
	
	public partial class mostrarTicketDosResult
	{
		
		private int _Ticket;
		
		private string _Producto;
		
		private string _Guiso;
		
		private int _Cantidad;
		
		private System.Nullable<decimal> _Precio;
		
		public mostrarTicketDosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ticket", DbType="Int NOT NULL")]
		public int Ticket
		{
			get
			{
				return this._Ticket;
			}
			set
			{
				if ((this._Ticket != value))
				{
					this._Ticket = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Producto", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Producto
		{
			get
			{
				return this._Producto;
			}
			set
			{
				if ((this._Producto != value))
				{
					this._Producto = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guiso", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guiso
		{
			get
			{
				return this._Guiso;
			}
			set
			{
				if ((this._Guiso != value))
				{
					this._Guiso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int NOT NULL")]
		public int Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Decimal(21,2)")]
		public System.Nullable<decimal> Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this._Precio = value;
				}
			}
		}
	}
	
	public partial class mostrarTotalResult
	{
		
		private System.Nullable<decimal> _Total;
		
		public mostrarTotalResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
	}
	
	public partial class mostrarCorteResult
	{
		
		private int _Codigo;
		
		private string _Nombre;
		
		private string _Guiso;
		
		private System.Nullable<int> _Cantidad;
		
		private System.Nullable<decimal> _Total;
		
		private string _Nombre_empleado;
		
		public mostrarCorteResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="Int NOT NULL")]
		public int Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this._Codigo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="VarChar(60) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this._Nombre = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Guiso", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string Guiso
		{
			get
			{
				return this._Guiso;
			}
			set
			{
				if ((this._Guiso != value))
				{
					this._Guiso = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cantidad", DbType="Int")]
		public System.Nullable<int> Cantidad
		{
			get
			{
				return this._Cantidad;
			}
			set
			{
				if ((this._Cantidad != value))
				{
					this._Cantidad = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Total", DbType="Decimal(38,2)")]
		public System.Nullable<decimal> Total
		{
			get
			{
				return this._Total;
			}
			set
			{
				if ((this._Total != value))
				{
					this._Total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Nombre empleado]", Storage="_Nombre_empleado", DbType="VarChar(92) NOT NULL", CanBeNull=false)]
		public string Nombre_empleado
		{
			get
			{
				return this._Nombre_empleado;
			}
			set
			{
				if ((this._Nombre_empleado != value))
				{
					this._Nombre_empleado = value;
				}
			}
		}
	}
	
	public partial class mostrarEmpleadosResult
	{
		
		private int _idEmpleado;
		
		private string _nombreEmpleado;
		
		private string _appEmpleado;
		
		private string _Usuario;
		
		private string _apmEmpleado;
		
		private string _Contraseña;
		
		private string _Permiso;
		
		public mostrarEmpleadosResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_idEmpleado", DbType="Int NOT NULL")]
		public int idEmpleado
		{
			get
			{
				return this._idEmpleado;
			}
			set
			{
				if ((this._idEmpleado != value))
				{
					this._idEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nombreEmpleado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string nombreEmpleado
		{
			get
			{
				return this._nombreEmpleado;
			}
			set
			{
				if ((this._nombreEmpleado != value))
				{
					this._nombreEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_appEmpleado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string appEmpleado
		{
			get
			{
				return this._appEmpleado;
			}
			set
			{
				if ((this._appEmpleado != value))
				{
					this._appEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Usuario", DbType="VarChar(50)")]
		public string Usuario
		{
			get
			{
				return this._Usuario;
			}
			set
			{
				if ((this._Usuario != value))
				{
					this._Usuario = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_apmEmpleado", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string apmEmpleado
		{
			get
			{
				return this._apmEmpleado;
			}
			set
			{
				if ((this._apmEmpleado != value))
				{
					this._apmEmpleado = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contraseña", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string Contraseña
		{
			get
			{
				return this._Contraseña;
			}
			set
			{
				if ((this._Contraseña != value))
				{
					this._Contraseña = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Permiso", DbType="Char(2) NOT NULL", CanBeNull=false)]
		public string Permiso
		{
			get
			{
				return this._Permiso;
			}
			set
			{
				if ((this._Permiso != value))
				{
					this._Permiso = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
